## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia

dist: xenial

os:
  - linux
  
env:
  - JULIA_CMDSTAN_HOME="$HOME/cmdstan-2.21.0/"
  
before_install:
  - OLDWD=`pwd`
  - cd ~
  - wget https://github.com/stan-dev/cmdstan/releases/download/v2.22.1/cmdstan-2.22.1.tar.gz
  - tar -xzpf cmdstan-2.22.1.tar.gz
  - make -C $JULIA_CMDSTAN_HOME build
  - cd $OLDWD
  
notifications:
  email: false
  
git:
  depth: 99999999
  
jobs:
  include:
    - stage: Test
      julia: 1.3
      os: linux
    - stage: Test
      julia: 1.4
      os: linux
    - stage: Test
      julia: nightly
      os: linux
